theme:           jekyll-theme-cayman
title:           Battleship
description:     Text based remake of the classic game with customization options for adding variety
is_user_page:    false
is_project_page: true
show_downloads:  true
